import { cv } from '@apx-ui/engine';

/* -------------------------------------------------------------------------- */
/*  Pagination — slot recipes                                                  */
/* -------------------------------------------------------------------------- */
/* One `cv()` per addressable DOM element so a theme override can target any
 * slot in isolation. The visual matrix the plan calls for — 4 variants × 7
 * colors × 3 sizes × 3 shapes = 252 cells — is fully addressable on the
 * `button` slot via the (variant × color × current) compound axis below.
 *
 * Size + shape are simple variants because they're orthogonal to the
 * variant/color treatment (a `pill` page button looks the same in every
 * variant; an `lg` page button is just taller).
 *
 * IMPORTANT: every utility class has to appear *literally* in source so
 * Tailwind v3's content scanner can pick it up. That's why each color's
 * rule is written out by hand instead of generated by a template string. */

/* -------------------------------------------------------------------------- */
/*  Root <nav>                                                                 */
/* -------------------------------------------------------------------------- */

export const paginationRootRecipe = cv({
  base: 'flex items-center gap-2 text-fg-default',
  variants: {
    size: {
      sm: 'text-xs',
      md: 'text-sm',
      lg: 'text-base',
    },
    justify: {
      start: 'justify-start',
      center: 'justify-center',
      end: 'justify-end',
      between: 'justify-between',
    },
    layout: {
      full: 'flex-wrap',
      compact: 'flex-nowrap',
      'pages-only': 'flex-nowrap',
      simple: 'flex-nowrap',
    },
  },
  defaultVariants: {
    size: 'md',
    justify: 'between',
    layout: 'full',
  },
});

/* -------------------------------------------------------------------------- */
/*  Page-number list                                                           */
/* -------------------------------------------------------------------------- */

export const paginationListRecipe = cv({
  base: 'flex items-center gap-1',
});

/* -------------------------------------------------------------------------- */
/*  Button (page-number + first/prev/next/last)                                */
/* -------------------------------------------------------------------------- */

/**
 * Single button surface used for both page-number cells and the chevron
 * navigation buttons. The same recipe handles:
 *
 *   - idle + hover treatment (variant-agnostic across colors)
 *   - "this is the current page" treatment (variant × color compound)
 *   - disabled treatment (universal — `disabled:` Tailwind utilities)
 *   - icon-only mode (square footprint regardless of label width)
 *
 * `current` is a boolean variant — the consumer passes `current={true}` on
 * the active page button. Color matters *only* for the current treatment:
 * idle/hover buttons render in neutral tones so a `<Pagination color="danger">`
 * doesn't paint every page button red.
 */
export const paginationButtonRecipe = cv({
  base: [
    'inline-flex items-center justify-center select-none',
    'font-medium tabular-nums whitespace-nowrap',
    'border border-transparent',
    'transition-[background-color,color,border-color,box-shadow]',
    'duration-fast ease-standard',
    'active:scale-[0.97] motion-reduce:active:scale-100',
    'outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-bg',
    'disabled:opacity-40 disabled:pointer-events-none',
    'data-[disabled=true]:opacity-40 data-[disabled=true]:pointer-events-none',
    'cursor-pointer disabled:cursor-not-allowed',
  ].join(' '),
  variants: {
    variant: {
      ghost: '',
      outline: '',
      soft: '',
      solid: '',
    },
    color: {
      primary: '',
      secondary: '',
      success: '',
      warning: '',
      danger: '',
      info: '',
      neutral: '',
    },
    size: {
      sm: 'h-8 min-w-8 px-2 text-xs [&_svg]:size-3.5',
      md: 'h-10 min-w-10 px-3 text-sm [&_svg]:size-4',
      lg: 'h-12 min-w-12 px-4 text-base [&_svg]:size-5',
    },
    shape: {
      square: 'rounded-md',
      rounded: 'rounded-lg',
      pill: 'rounded-full',
    },
    current: {
      true: 'font-semibold',
      false: '',
    },
    iconOnly: {
      true: 'aspect-square px-0',
      false: '',
    },
  },
  compoundVariants: [
    /* ------------------------------------------------------------------ */
    /*  Idle / hover — variant-only (color-agnostic)                       */
    /* ------------------------------------------------------------------ */
    {
      variant: 'ghost',
      current: false,
      class: 'bg-transparent text-fg-default hover:bg-bg-subtle',
    },
    {
      variant: 'outline',
      current: false,
      class: 'bg-transparent text-fg-default border-border hover:bg-bg-subtle',
    },
    {
      variant: 'soft',
      current: false,
      class: 'bg-bg-subtle text-fg-default hover:bg-bg-subtle/60',
    },
    {
      variant: 'solid',
      current: false,
      class: 'bg-bg-paper text-fg-default border-border hover:bg-bg-subtle',
    },

    /* ------------------------------------------------------------------ */
    /*  Current-page treatment — variant × color (28 rules)                */
    /* ------------------------------------------------------------------ */

    /* ── ghost current ────────────────────────────────────────────────── */
    {
      variant: 'ghost',
      color: 'primary',
      current: true,
      class: 'bg-primary-subtle text-primary hover:bg-primary-subtle focus-visible:ring-primary',
    },
    {
      variant: 'ghost',
      color: 'secondary',
      current: true,
      class:
        'bg-secondary-subtle text-secondary hover:bg-secondary-subtle focus-visible:ring-secondary',
    },
    {
      variant: 'ghost',
      color: 'success',
      current: true,
      class: 'bg-success-subtle text-success hover:bg-success-subtle focus-visible:ring-success',
    },
    {
      variant: 'ghost',
      color: 'warning',
      current: true,
      class: 'bg-warning-subtle text-warning hover:bg-warning-subtle focus-visible:ring-warning',
    },
    {
      variant: 'ghost',
      color: 'danger',
      current: true,
      class: 'bg-danger-subtle text-danger hover:bg-danger-subtle focus-visible:ring-danger',
    },
    {
      variant: 'ghost',
      color: 'info',
      current: true,
      class: 'bg-info-subtle text-info hover:bg-info-subtle focus-visible:ring-info',
    },
    {
      variant: 'ghost',
      color: 'neutral',
      current: true,
      class: 'bg-neutral-subtle text-neutral hover:bg-neutral-subtle focus-visible:ring-neutral',
    },

    /* ── outline current ──────────────────────────────────────────────── */
    {
      variant: 'outline',
      color: 'primary',
      current: true,
      class:
        'bg-primary text-primary-contrast border-primary hover:bg-primary-hover focus-visible:ring-primary',
    },
    {
      variant: 'outline',
      color: 'secondary',
      current: true,
      class:
        'bg-secondary text-secondary-contrast border-secondary hover:bg-secondary-hover focus-visible:ring-secondary',
    },
    {
      variant: 'outline',
      color: 'success',
      current: true,
      class:
        'bg-success text-success-contrast border-success hover:bg-success-hover focus-visible:ring-success',
    },
    {
      variant: 'outline',
      color: 'warning',
      current: true,
      class:
        'bg-warning text-warning-contrast border-warning hover:bg-warning-hover focus-visible:ring-warning',
    },
    {
      variant: 'outline',
      color: 'danger',
      current: true,
      class:
        'bg-danger text-danger-contrast border-danger hover:bg-danger-hover focus-visible:ring-danger',
    },
    {
      variant: 'outline',
      color: 'info',
      current: true,
      class:
        'bg-info text-info-contrast border-info hover:bg-info-hover focus-visible:ring-info',
    },
    {
      variant: 'outline',
      color: 'neutral',
      current: true,
      class:
        'bg-neutral text-neutral-contrast border-neutral hover:bg-neutral-hover focus-visible:ring-neutral',
    },

    /* ── soft current ─────────────────────────────────────────────────── */
    /* Tinted background, colored text — the most quietly emphatic option.
     * Uses the same `subtle` token as ghost-current; the visual difference
     * comes from the surrounding idle buttons which sit on `bg-bg-subtle`. */
    {
      variant: 'soft',
      color: 'primary',
      current: true,
      class: 'bg-primary-subtle text-primary hover:bg-primary-subtle focus-visible:ring-primary',
    },
    {
      variant: 'soft',
      color: 'secondary',
      current: true,
      class:
        'bg-secondary-subtle text-secondary hover:bg-secondary-subtle focus-visible:ring-secondary',
    },
    {
      variant: 'soft',
      color: 'success',
      current: true,
      class: 'bg-success-subtle text-success hover:bg-success-subtle focus-visible:ring-success',
    },
    {
      variant: 'soft',
      color: 'warning',
      current: true,
      class: 'bg-warning-subtle text-warning hover:bg-warning-subtle focus-visible:ring-warning',
    },
    {
      variant: 'soft',
      color: 'danger',
      current: true,
      class: 'bg-danger-subtle text-danger hover:bg-danger-subtle focus-visible:ring-danger',
    },
    {
      variant: 'soft',
      color: 'info',
      current: true,
      class: 'bg-info-subtle text-info hover:bg-info-subtle focus-visible:ring-info',
    },
    {
      variant: 'soft',
      color: 'neutral',
      current: true,
      class: 'bg-neutral-subtle text-neutral hover:bg-neutral-subtle focus-visible:ring-neutral',
    },

    /* ── solid current ────────────────────────────────────────────────── */
    {
      variant: 'solid',
      color: 'primary',
      current: true,
      class:
        'bg-primary text-primary-contrast border-primary hover:bg-primary-hover focus-visible:ring-primary',
    },
    {
      variant: 'solid',
      color: 'secondary',
      current: true,
      class:
        'bg-secondary text-secondary-contrast border-secondary hover:bg-secondary-hover focus-visible:ring-secondary',
    },
    {
      variant: 'solid',
      color: 'success',
      current: true,
      class:
        'bg-success text-success-contrast border-success hover:bg-success-hover focus-visible:ring-success',
    },
    {
      variant: 'solid',
      color: 'warning',
      current: true,
      class:
        'bg-warning text-warning-contrast border-warning hover:bg-warning-hover focus-visible:ring-warning',
    },
    {
      variant: 'solid',
      color: 'danger',
      current: true,
      class:
        'bg-danger text-danger-contrast border-danger hover:bg-danger-hover focus-visible:ring-danger',
    },
    {
      variant: 'solid',
      color: 'info',
      current: true,
      class:
        'bg-info text-info-contrast border-info hover:bg-info-hover focus-visible:ring-info',
    },
    {
      variant: 'solid',
      color: 'neutral',
      current: true,
      class:
        'bg-neutral text-neutral-contrast border-neutral hover:bg-neutral-hover focus-visible:ring-neutral',
    },

    /* Note: idle (current=false) buttons rely on the DS theme's default focus
     * ring (`ringColor.DEFAULT` from the Tailwind preset → `--sds-focus-ring`).
     * We don't tint the idle focus ring per `color` prop on purpose: a
     * `color="danger"` Pagination shouldn't paint every non-current page
     * button's focus ring red — the danger accent is reserved for the
     * current-page treatment only. The base class
     * `focus-visible:ring-offset-bg` keeps the ring contrasted against any
     * surface variant. */
  ],
  defaultVariants: {
    variant: 'ghost',
    color: 'primary',
    size: 'md',
    shape: 'square',
    current: false,
    iconOnly: false,
  },
});

/* -------------------------------------------------------------------------- */
/*  Ellipsis cell                                                              */
/* -------------------------------------------------------------------------- */

export const paginationEllipsisRecipe = cv({
  base: 'inline-flex items-center justify-center text-fg-muted select-none',
  variants: {
    size: {
      sm: 'h-8 min-w-8 px-1 text-xs',
      md: 'h-10 min-w-10 px-2 text-sm',
      lg: 'h-12 min-w-12 px-3 text-base',
    },
  },
  defaultVariants: { size: 'md' },
});

/* -------------------------------------------------------------------------- */
/*  Range label ("1–25 of 120")                                                */
/* -------------------------------------------------------------------------- */

export const paginationRangeLabelRecipe = cv({
  base: 'inline-flex items-center text-fg-muted tabular-nums',
  variants: {
    size: {
      sm: 'text-xs',
      md: 'text-sm',
      lg: 'text-base',
    },
  },
  defaultVariants: { size: 'md' },
});

/* -------------------------------------------------------------------------- */
/*  Size picker wrapper                                                        */
/* -------------------------------------------------------------------------- */

export const paginationSizePickerRecipe = cv({
  base: 'inline-flex items-center gap-2 text-fg-muted',
  variants: {
    size: {
      sm: 'text-xs',
      md: 'text-sm',
      lg: 'text-base',
    },
  },
  defaultVariants: { size: 'md' },
});
